### ISSUE TITLE
Build error using version 0.1.0 on opam

### ISSUE THREAD

**Issue by Gbury** [ujamjar/sattools#1]
When trying to install sattools using opam, the latest and only version available is 0.1.0, which, on my computer fails to build with the following error:

```
#=== ERROR while installing sattools.0.1.0 ====================================#
# opam-version 1.2.2
# os           linux
# command      make build
# path         /home/guigui/.opam/4.04.0+flambda/build/sattools.0.1.0
# compiler     4.04.0+flambda
# exit-code    2
# env-file     /home/guigui/.opam/4.04.0+flambda/build/sattools.0.1.0/sattools-30517-1872ec.env
# stdout-file  /home/guigui/.opam/4.04.0+flambda/build/sattools.0.1.0/sattools-30517-1872ec.out
# stderr-file  /home/guigui/.opam/4.04.0+flambda/build/sattools.0.1.0/sattools-30517-1872ec.err
### stdout ###
# [...]
# minisat/minisat_stubgen.byte -ml > minisat/minisat_stubs.ml
# minisat/minisat_stubgen.byte -c > minisat/minisat_cstubs.c
# g++ -c -shared -fPIC minisat/minisat_intf.cc -o minisat/minisat_intf.o
# + g++ -c -shared -fPIC minisat/minisat_intf.cc -o minisat/minisat_intf.o
# In file included from minisat/minisat_intf.cc:1:0:
# minisat/minisat_intf.h:4:33: fatal error: minisat/core/Solver.h: No such file or directory
#  #include <minisat/core/Solver.h>
#                                  ^
# compilation terminated.
# Command exited with code 1.
### stderr ###
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-tag' 'debug'
# [...]
#      'cryptominisat/ocryptominisat.a' 'cryptominisat/ocryptominisat.cmxs'
#      'cryptominisat/ocryptominisat.cmxa' 'cryptominisat/ocryptominisat.cma'
#      'cryptominisat/cryptominisat.cmx' 'cryptominisat/cryptominisat.cmi'
#      'cryptominisat/cryptominisat.mli'
#      'cryptominisat/cryptominisat_stubs.cmx'
#      'cryptominisat/cryptominisat_bindings.cmx'
#      'cryptominisat/cryptominisat_bindings.cmi'
#      'cryptominisat/cryptominisat_bindings.mli']: exited with 10
# make: *** [Makefile:11: build] Error 1
```

**Comment by andrewray** [comment]
Which OS distro are you using?  Do you know where the minisat headers installed on it?

**Comment by Gbury** [comment]
I'm using archlinux, but I currently have no idea where the minisat headers are installed. I'll try and look.

**Comment by andrewray** [comment]
They might possibly be in a different package (minisat-dev or somesuch)?

On ubuntu they are installed in

```
/usr/include/minisat/...
```

**Comment by Gbury** [comment]
Doesn't exist on my install, maybe the 'minisat' package actually doesn't install the lib but only the bin ? I'll try the minisat-git package

**Comment by Gbury** [comment]
So, installing the minisat-git package actually solved the problem. Though now I have the same problem with picosat... Seems like the archlinux AUR packages make sometimes strange choices.

**Comment by andrewray** [comment]
I had some recent trouble getting picosat to install on both centos / ubuntu (headers were in different places)  A recent commit fixes it, should you see a similar problem

```
opam pin add -k git sattools https://github.com/ujamjar/sattools
```

**Comment by Gbury** [comment]
So far, from what I've seen, my picosat install also lacks the lib (it only installs the binaries, even though it builds from the source).

**Comment by andrewray** [comment]
Ok.  I had a feeling this might all be an issue.  The build assumes that the existence of the binary implies the libary is also installed.  This isnt really true on any OS, but was a simple.

I'll open an issue on this, and have a think about a fix.
