### ISSUE TITLE
Top-level Minisat module clashes with the minisat opam package

### ISSUE THREAD

**Issue by Gbury** [ujamjar/sattools#3]
While trying to do some comparative benchmarks between sat solvers in ocaml, I found out that both the `minisat` package and the `sattools.minisat` package define a `Minisat` top-level module, which prevents using them both in the same project.
Unfortunately, I don't know of a better solution than to rename one of the two modules, which would likely break retro-compatbility. Still, could renaming the `Minisat` top-level module to something like `Sattools.Minisat` be an acceptable solution ?
(cc @c-cube author of the `minisat` package)

**Comment by andrewray** [comment]
I would be happy enough for the Minisat (and related Cryptominisat/Picosat) modules to be renamed.

There are designed to be used via the `Sattools.Libs.get_solver` interface and so it wouldn't break any of my code.

I don't think they can be put underneath a packed interface (ie `Sattools.XXX`) as they are meant to be dynamically loaded.  Perhaps

* `<Solver>` -> `<Solver>_raw_intf`
* `<Solver>_bindings` stays the same

**Comment by Gbury** [comment]
That would look good to me.

**Comment by Gbury** [comment]
Though it would still be quite confusing for new users of both libraries, who could reasonnably expect the `Minisat_*` modules to be part of the `minisat` package.

**Comment by andrewray** [comment]
Ported to jbuilder and renamed.
