### ISSUE TITLE
Installation of sub-modules

### ISSUE THREAD

**Issue by Gbury** [ujamjar/sattools#5]
I tried to pin `sattools` to the github repo, and it succesfully installed, but it didn't seem to detect neither minisat nor cryptominisat, thus only the `sattools` ocamlfind package was installed, and not the `sattools.minisat` and `sattools.cryptominisat` ocamlfind libs that give access to the bindings.

I tried installing version 0.1.0 and it works as expected: it detects and successfully install the bindings for minisat and cryptominisat, which suggests the problem may be due to the recent switch to jbuilder ?

**Comment by andrewray** [comment]
You need to pin `sattools-minisat` and `sattools-cryptominisat` to this repository also.  Then access the ocamlfind libraries with these new names.  The packages are totally separate now

**Comment by Gbury** [comment]
Oh, thanks !
I know it's more of an opam issue, but it is really necessary to pin the same repo three times to have access to all the packages ?

**Comment by andrewray** [comment]
With jbuilder, yes.

Separating the packages also means I don't have to worry about all sorts of install checks to decide exactly what is installable.  sattools will always work, and the other libraries will install if the C dependencies are met.

**Comment by Gbury** [comment]
I agree with the fact that having separate packages is better.

 I was only wondering if maybe, when pinning opam could magically detect the 4 `*.opam` files and adds all packages instead of having to manually pin each one, but it's not related to sattools.

Thanks again !

**Comment by andrewray** [comment]
I don't think it's possible currently, but with many other packages heading in this direction maybe opam will add the option.
